  inbound_policy: "DROP"
  inbound:
    - rule_name: "allow_ssh_inbound"
      action: "accept"
      protocol: "tcp"
      ip: "any"
      port: 22
      description: "Block inbound SSH traffic from local network"

    - rule_name: "allow_web_inbound"
      action: "accept"
      protocol: "udp"
      ip: "any"
      port_range:
        start: 50
        end: 443
      description: "Allow inbound HTTP and HTTPS traffic from any source"

    - rule_name: "allow_icmp_inbound"
      action: "accept"
      protocol: "icmp"
      ip: "any"
      description: "Allow all inbound ICMP traffic"

  outbound_policy: "DROP"
  outbound:
    - rule_name: "allow_ssh_outbound"
      action: "accept"
      protocol: "tcp"
      ip: "any"
      port: 22
      description: "Allow outbound DNS queries to Google DNS"
    - rule_name: "allow_icmp_outbound"
      action: "accept"
      protocol: "icmp"
      ip: "any"
      description: "Block all outbound ICMP traffic to specified network"
    - rule_name: "allow_smtp_outbound"
      action: "accept"
      protocol: "tcp"
      ip: "any"
      port: 25
      description: "Allow outbound SMTP traffic to any destination"
    - rule_name: "allow_web_inbound"
      action: "accept"
      protocol: "udp"
      ip: "any"
      port_range:
        start: 50
        end: 443
      description: "Allow inbound HTTP and HTTPS traffic from any source"
