firewall:
  interfaces:
    - name: eth0
      type: physical
      enabled: true
      xdp_attach_mode: skb
      inbound:
        default_policy: DROP
        rules:
          - protocol: icmp
            source_ip: any
            destination_ip: any
            source_port: any
            destination_port: any
            action: ACCEPT
            description: "Autorise tous les paquets ICMP (ping, etc.)"

      outbound:
        default_policy: DROP
        rules:
          - protocol: icmp
            source_ip: any
            destination_ip: any
            source_port: any
            destination_port: any
            action: DROP
            description: "Autorise tous les paquets ICMP (ping, etc.)"