firewall:
  interfaces:
    - name: lo
      type: physical
      enabled: true

      inbound:
        default_policy: DROP
        rules:
          - protocol: icmp
            source_ip: any
            destination_ip: any
            source_port: any
            destination_port: any
            icmp_type: 0        # <- important : signifie "tous les types"
            action: ACCEPT
            description: "Autorise tous les paquets ICMP (ping, etc.)"

      outbound:
        default_policy: ACCEPT
        rules: []